package legalguard.leoncuhk_awesome_quant_ai

# Guardrail for: leoncuhk/awesome-quant-ai
# Sector: CIB | Modality: rag_document | Risk tier: unclassified
#
# This is a default-deny stub generated by LegalGuard. Fill in the real
# conditions for each regulatory mandate listed in REGULATORY_PROVENANCE.md
# before treating this as enforceable -- see that file for what each clause
# actually requires.

# --- Sector compliance thresholds (see policies/thresholds.json for full citations) ---
material_nonpublic_info_flag_required := true  # Baseline expectation under insider-trading/MNPI surveillance regimes -- confirm against the firm's information barrier policy.
# human_review_confirmed -- TODO: Structural requirement, not a regulatory figure -- every guardrail needs an explicit human-review signal before allowing a decision through. (not enforced until set)

# None of the thresholds above are wired into `allow` yet -- LegalGuard
# doesn't know this system's actual input schema, so it won't guess field
# names for you. Reference them (e.g. `input.transaction_amount_usd >=
# ctr_filing_threshold_usd`) once you know what your pipeline actually sends.

default allow := false

allow if {
    input.compliance_checks_passed == true
    input.human_review_confirmed == true
}
